<?php
return [
'hostKeys' => [
    '' => '本站',
    'mzk' => '美宅客',
	'55jia' => '55jia',
    'toteme' => '途睿',
    'yuezw' => '悦装',
    'hl' => '搜狗hl',
    'hd3' => '360维纳亚',
    'hds' => '搜狗维纳亚',
    'jz' => '极装吉住',
	'tbz' => '兔班长',
],
'spreadUrlTypes' => [
    'lzztbj' => [
        'name' => '柳州中宅装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'lzzbj' => [
        'name' => '柳州中宅装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'lzzsj' => [
        'name' => '柳州中宅装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jinztbj' => [
        'name' => '今朝装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jinzbj' => [
        'name' => '今朝装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jinzsj' => [
        'name' => '今朝装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jhd3' => [
        'name' => '50家315活动',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'jlaof' => [
        'name' => '50家老房',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'jquanan' => [
        'name' => '50家全案',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'jdas' => [
        'name' => '50家国际大师',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'mnew' => [
        'name' => '美宅客活动页',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'mnewbj' => [
        'name' => '美宅客移动端报价',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'mnewlf' => [
        'name' => '美宅客移动端量房',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    /*'mzkn' => [
        'name' => '美宅客活动页',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],*/
    'jzhd' => [
        'name' => '极装吉住315活动',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'ldoutbj' => [
        'name' => '绿豆装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'ldoubj' => [
        'name' => '绿豆装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'ldousj' => [
        'name' => '绿豆装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jkjtbj' => [
        'name' => '九空间装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jkjbj' => [
        'name' => '九空间装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jkjsj' => [
        'name' => '九空间装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'j50tbj' => [
        'name' => '50家装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'j50bj' => [
        'name' => '50家装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'j50sj' => [
        'name' => '50家装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'dzrtbj' => [
        'name' => '大自然装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'dzrbj' => [
        'name' => '大自然装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'dzrsj' => [
        'name' => '大自然装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'yzfhb' => [
        'name' => '业之峰环保（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzfds' => [
        'name' => '业之峰大室（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzfbs' => [
        'name' => '业之峰别墅（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzftbj' => [
        'name' => '业之峰装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzfbj' => [
        'name' => '业之峰装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzfsj' => [
        'name' => '业之峰装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'sftbj' => [
        'name' => '盛发装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sfbj' => [
        'name' => '盛发装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sfsj' => [
        'name' => '盛发装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jrzjtbj' => [
        'name' => '居然之家报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jrzjbj' => [
        'name' => '居然之家报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jrsnzb' => [
        'name' => '居然之家十年（居然)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jrdp' => [
        'name' => '居然之家大牌汇（居然)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'jrzj' => [
        'name' => '居然之家PC（居然)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'jrzjsj' => [
        'name' => '居然之家PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jztbj' => [
        'name' => '极装吉住报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jzbj' => [
        'name' => '极装吉住报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jzsj' => [
        'name' => '极装吉住PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'tstbj' => [
        'name' => '天盛装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tsbj' => [
        'name' => '天盛装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tssj' => [
        'name' => '天盛装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'tshd' => [
        'name' => '天盛装饰活动',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'cjhlsj' => [
        'name' => '诚聚互联PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'yzwtbj' => [
        'name' => '悦装网报价(土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzwbj' => [
        'name' => '悦装网报价(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzwsj' => [
        'name' => '悦装网PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'mzkbj' => [
        'name' => '美宅客报价(mzk)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'mzkhd' => [
        'name' => '美宅客PC（mzk)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],

    'liangfang' => [
        'name' => '免费量房(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'bjnew' => [
        'name' => '17报价(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'manyi' => [
        'name' => '满意(图满意）',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sjlfb' => [
        'name' => '装修报名（17house)-百姓',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'sj' => [
        'name' => 'PC报名（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'bjmh' => [
        'name' => '美猴报价报名（jia)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],

    'znbj' => [
        'name' => '报价(土巴兔)测试用',
        'pc' => true,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sheji' => [
        'name' => '免费设计(兔狗)测试用',
        'pc' => true,
        'mobile' => true,
        'main' => 'main',
    ],
    'tobj' => [
        'name' => '报价(土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'wlbj' => [
        'name' => '报价(万链)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sdtbj' => [
        'name' => '圣点装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sdbj' => [
        'name' => '圣点装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'sdsj' => [
        'name' => '圣点装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
],
];
