<?php
return [
'hostKeys' => [
    '' => '本站',
    'mzk' => '美宅客',
	'55jia' => '55jia',
    'toteme' => '途睿',
    'yuezw' => '悦装',
    'hl' => '搜狗hl',
    'hd3' => '360维纳亚',
    'hds' => '搜狗维纳亚',
    'jz' => '极装吉住',
	'tbz' => '兔班长',
	'tbzsh' => '兔班长上海',
	'jzwet' => '诗香教育',
	'dediga' => '360拼框',
],
'spreadUrlTypes' => [
    'ypjjzsj' => [
        'name' => '优品家（家装设计）',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'ypjtbj' => [
        'name' => '优品家装饰家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'ypjsj' => [
        'name' => '优品家装饰家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jjjznbj' => [
        'name' => '就近家装（柠檬报价)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jjjzjzsj' => [
        'name' => '就近家装（家装设计）',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jjjztbj' => [
        'name' => '就近家装装饰家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    /*'jjjzbj' => [
        'name' => '就近家装装饰家装报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],*/
    'jjjzpcbj' => [
        'name' => '就近家装装饰家装PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'jjjzsj' => [
        'name' => '就近家装装饰家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'aikjtbj' => [
        'name' => '爱空间装饰家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    /*'aikjbj' => [
        'name' => '爱空间装饰家装报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],*/
    'aikjpcbj' => [
        'name' => '爱空间装饰家装PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'aikjsj' => [
        'name' => '爱空间装饰家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'opyzsj' => [
        'name' => '欧派雅致三居',
        'pc' => false,
        'mobile' => true,
        'main' => false,
    ],
    'opztcg' => [
        'name' => '欧派整体橱柜',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'opxhx' => [
        'name' => '欧派小户型',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'opkct' => [
        'name' => '欧派客餐厅',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'opjpjz' => [
        'name' => '欧派精品家装',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'optbj' => [
        'name' => '欧派报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'opsj' => [
        'name' => '欧派PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'jsytbj' => [
        'name' => '金三优装饰家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    /*'jsybj' => [
        'name' => '金三优装饰家装报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],*/
    'jsypcbj' => [
        'name' => '金三优装饰家装PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'jsysj' => [
        'name' => '金三优装饰家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'mdtbj' => [
        'name' => '闽东装饰家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'mdbj' => [
        'name' => '闽东装饰家装报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'mdpcbj' => [
        'name' => '闽东装饰家装PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
        'noShow' => true,
    ],
    'mdsj' => [
        'name' => '闽东装饰家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'fktbj' => [
        'name' => '梵客家装报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'fkbj' => [
        'name' => '梵客家装报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'fkpcbj' => [
        'name' => '梵客家装PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
        'noShow' => true,
    ],
    'fksj' => [
        'name' => '梵客家装PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'lzztbj' => [
        'name' => '柳州中宅装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'lzzbj' => [
        'name' => '柳州中宅装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'lzzsj' => [
        'name' => '柳州中宅装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jinztbj' => [
        'name' => '今朝装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jinzbj' => [
        'name' => '今朝装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jinzsj' => [
        'name' => '今朝装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'mnew' => [
        'name' => '美宅客活动页',
        'pc' => true,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'mnewbj' => [
        'name' => '美宅客移动端报价',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'mnewlf' => [
        'name' => '美宅客移动端量房',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'mzkn' => [
        'name' => '美宅客活动页',
        'pc' => true,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
        'noShow' => true,
    ],
    'jzhd' => [
        'name' => '极装吉住315活动',
        'pc' => true,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
        'noShow' => true,
    ],
    'ldouhd' => [
        'name' => '绿豆装饰活动',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'ldouext' => [
        'name' => '绿豆活动页',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'ldoutbj' => [
        'name' => '绿豆装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'ldoubj' => [
        'name' => '绿豆装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'ldousj' => [
        'name' => '绿豆装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jkjtbj' => [
        'name' => '九空间装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jkjbj' => [
        'name' => '九空间装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jkjsj' => [
        'name' => '九空间装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'j50tbj' => [
        'name' => '50家装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'j50bj' => [
        'name' => '50家装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'j50sj' => [
        'name' => '50家装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jhd3' => [
        'name' => '50家315活动',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'jlaof' => [
        'name' => '50家老房',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'jquanan' => [
        'name' => '50家全案',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'jdas' => [
        'name' => '50家国际大师',
        'pc' => false,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'dzrtbj' => [
        'name' => '大自然装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'dzrbj' => [
        'name' => '大自然装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'dzrsj' => [
        'name' => '大自然装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'yzfhb' => [
        'name' => '业之峰环保（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzfds' => [
        'name' => '业之峰大室（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzfbs' => [
        'name' => '业之峰别墅（客户)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
    ],
    'yzftbj' => [
        'name' => '业之峰装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzfbj' => [
        'name' => '业之峰装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'yzfsj' => [
        'name' => '业之峰装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'sftbj' => [
        'name' => '盛发装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sfbj' => [
        'name' => '盛发装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sfsj' => [
        'name' => '盛发装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jrzjtbj' => [
        'name' => '居然之家报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jrzjbj' => [
        'name' => '居然之家报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jrsnzb' => [
        'name' => '居然之家十年（居然)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jrdp' => [
        'name' => '居然之家大牌汇（居然)',
        'pc' => true,
        'mobile' => true,
        'main' => false,
        'noShow' => true,
    ],
    'jrzj' => [
        'name' => '居然之家PC（居然)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
        'noShow' => true,
    ],
    'jrzjsj' => [
        'name' => '居然之家PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'jztbj' => [
        'name' => '极装吉住报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jzbj' => [
        'name' => '极装吉住报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'jzsj' => [
        'name' => '极装吉住PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'tstbj' => [
        'name' => '天盛装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tsbj' => [
        'name' => '天盛装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tssj' => [
        'name' => '天盛装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'tshd' => [
        'name' => '天盛装饰活动',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'cjhlsj' => [
        'name' => '诚聚互联PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'yzwtbj' => [
        'name' => '悦装网报价(土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'yzwbj' => [
        'name' => '悦装网报价(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'yzwsj' => [
        'name' => '悦装网PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'mzkbj' => [
        'name' => '美宅客报价(mzk)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'mzkhd' => [
        'name' => '美宅客PC（mzk)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],

    'liangfang' => [
        'name' => '免费量房(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'bjnew' => [
        'name' => '17报价(17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'manyi' => [
        'name' => '满意(图满意）',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sjlfb' => [
        'name' => '装修报名（17house)-百姓',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sj' => [
        'name' => 'PC报名（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'bjmh' => [
        'name' => '美猴报价报名（jia)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
        'noShow' => true,
    ],

    'znbj' => [
        'name' => '报价(土巴兔)测试用',
        'pc' => true,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sheji' => [
        'name' => '免费设计(兔狗)测试用',
        'pc' => true,
        'mobile' => true,
        'main' => 'main',
        'noShow' => true,
    ],
    'tobj' => [
        'name' => '报价(土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'wlbj' => [
        'name' => '报价(万链)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sdtbj' => [
        'name' => '圣点装饰报价（土巴兔)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sdbj' => [
        'name' => '圣点装饰报价（17house)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'sdsj' => [
        'name' => '圣点装饰PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
        'noShow' => true,
    ],
    'tbzsj' => [
        'name' => '兔班长PC（jia)',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
    'tbzpcbj' => [
        'name' => '兔班长PC（报价)',
        'pc' => true,
        'mobile' => false,
        'main' => false,
    ],
    'tbz' => [
        'name' => '兔班长',
        'pc' => true,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tbzsjlf' => [
        'name' => '兔班长设计量房',
        'pc' => true,
        'mobile' => true,
        'main' => 'main-tbz',
    ],
    'tbznbj' => [
        'name' => '兔班长（柠檬报价)',
        'pc' => false,
        'mobile' => true,
        'main' => 'main-base',
    ],
    'tbzjzsj' => [
        'name' => '兔班长（家装设计）',
        'pc' => true,
        'mobile' => false,
        'main' => 'main-base',
    ],
],
];
