<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/jquery-1.8.3.min.js"></script>
<script src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/public.js" type="text/javascript"></script>
<script src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/platj_util.js" type="text/javascript"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/index.js"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/getattentioncountbyajax.js"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/js/addpageview.js"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/mui.js"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/js/tongji.js"></script>
<script type="text/javascript" src="http://60.205.145.0/filesys/spider/pages/asset/platj/m/js/tongji_m.js"></script>
