<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/jquery-1.8.3.min.js"></script>
<script src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/public.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/platj_util.js" type="text/javascript"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/index.js"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/getattentioncountbyajax.js"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/js/addpageview.js"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/mui.js"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/js/tongji.js"></script>
<script type="text/javascript" src="<?= Yii::getAlias('@asseturl'); ?>/house/platj/m/js/tongji_m.js"></script>
