<?php
return [
    'commercial' => [
        'huazhuangpinlei' => '化妆品',
        'fuzhuanglei' => '服装',
        'qichelei' => '汽车',
        'chanpinlei' => '产品',
        'youxidianying' => '游戏电影',
        'nianlidapian' => '年历大片',
        'xiebaolei' => '鞋包',
    ],
    'fashion' => [
        'nuzhuang' => '女装',
        'nanzhuang' => '男装',
        'tongzhuang' => '童装',
        'neiyiyongzhuang' => '内衣泳装',
        'lifu' => '礼服',
        'niuzai' => '牛仔',
        'xiebaolei' => '鞋包',
        'gaojidingzhi' => '高级定制',
        'picaolei' => '皮草',
    ],
    'star' => [
        'nanyiren' => '男艺人',
        'nuyiren' => '女艺人',
        'xianzuxuanchuan' => '见组宣传',
        'yirendaiyan' => '艺人代言',
        'fuguyuheibai' => '复古与黑白',
        'waijingdapian' => '外景大片',
        'weimeidapian' => '唯美大片',
        'xinggandapian' => '性感大片',
        'shineirenxiang' => '室内人像',
        'chuangyirenxiang' => '创意人像',
    ],
    'people' => [
        'fuguhuayi' => '复古画意',
        'heibaidapian' => '黑白大片',
        'oumeishishang' => '欧美时尚',
        'sifangsheying' => '私房摄影',
        'xinggandapian' => '性感大片',
        'lupai' => '旅拍',
        'chuangyishijue' => '创意视觉',
        'jingtaidianying' => '静态电影',
        'weimeirenxiang' => '唯美人像',
        'waijingrenxiang' => '外景人像',
    ],
    'wedding' => [
        'fuguhuayi' => '复古画意',
        'heibaidapian' => '黑白大片',
        'oumeidapian' => '欧美大片',
        'huanjingrenxiang' => '环境人像',
        'mingxinghunsha' => '明星婚纱',
        'lupai' => '旅拍',
        'shishangdapian' => '时尚大片',
        'yunfuqinzi' => '孕妇亲子',
    ],
];
