<?php 
return [
    'site-index' => [
		'name' => '首页',
		'pc-url' => '/',
		'mobile-url' => '/',
        'source-url' => '/',
    ],
    'aboutus-desc' => [
		'name' => '关于我们',
		'pc-url' => '/desc.html',
		'mobile-url' => '/desc.html',
        'source-url' => '/liaojie/',
		'nofollow' => true,
    ],
    'aboutus-company' => [
		'name' => '公司介绍',
		'pc-url' => '/company.html',
		'mobile-url' => '/company.html',
        'source-url' => '/gongsi/',
		'nofollow' => true,
    ],
    'aboutus-contactus' => [
		'name' => '联系我们',
		'pc-url' => '/contactus.html',
		'mobile-url' => '/contactus.html',
        'source-url' => '/contactus/',
		'nofollow' => true,
    ],
    'aboutus-joinus' => [
		'name' => '加入我们',
		'pc-url' => '/joinus.html',
		'mobile-url' => '/joinus.html',
        'source-url' => '/jiaru/',
		'nofollow' => true,
    ],
    'aboutus-customer' => [
		'name' => '合作客户',
		'pc-url' => '/customer.html',
		'mobile-url' => '/customer.html',
        'source-url' => '/kehu/',
		'nofollow' => true,
    ],
    'aboutus-star' => [
		'name' => '合作艺人',
		'pc-url' => '/star.html',
		'mobile-url' => '/star.html',
        'source-url' => '/yiren/',
		'nofollow' => true,
    ],
    'tag-list' => [
        'no-sitemap' => true,
		'name' => '标签列表',
		'pc-url' => '/tag/huazhuangpinlei/',
		'mobile-url' => '/tag/huazhuangpinlei/',
        'source-url' => '/commercials/t_101.html',
    ],
    'info-list' => [
        'no-sitemap' => true,
		'name' => '新闻列表',
		'pc-url' => '/info/',
		'mobile-url' => '/info/',
        'source-url' => '/news/',
    ],
    'info-show' => [
        'no-sitemap' => true,
		'name' => '新闻内容',
		'pc-url' => '/info/1.html',
		'mobile-url' => '/info/1.html',
        'source-url' => '/news/571610206.html',
    ],
    'service-list' => [
        'no-sitemap' => true,
		'name' => '服务列表',
        'only' => ['eale', 'ieale'],
		'pc-url' => '/service/',
		'mobile-url' => '/service/',
        'source-url' => '/service/',
    ],
    'service-show' => [
        'no-sitemap' => true,
		'name' => '服务内容',
        'only' => ['eale', 'ieale'],
		'pc-url' => '/service/1.html',
		'mobile-url' => '/service/1.html',
        'source-url' => '/service/441610200.html',
    ],
    'sample-star' => [
        'no-sitemap' => true,
		'name' => '明星摄影',
        'only' => ['eale', 'ieale'],
		'pc-url' => '/star/',
		'mobile-url' => '/star/',
		'source-url' => '/stars/',
    ],
    'sample-commercial' => [
        'no-sitemap' => true,
		'name' => '广告摄影',
        'only' => 'eale',
		'pc-url' => '/commercial/',
		'mobile-url' => '/commercial/',
		'source-url' => '/commercials/',
    ],
    'sample-fashion' => [
        'no-sitemap' => true,
		'name' => '服装摄影',
        'only' => 'eale',
		'pc-url' => '/fashion/',
		'mobile-url' => '/fashion/',
		'source-url' => '/fashions/',
    ],
    'sample-people' => [
        'no-sitemap' => true,
		'name' => '个人写真',
        'only' => 'ieale',
		'pc-url' => '/people/',
		'mobile-url' => '/people/',
		'source-url' => '/peoples/',
    ],
    'sample-wedding' => [
        'no-sitemap' => true,
		'name' => '婚纱摄影',
        'only' => 'ieale',
		'pc-url' => '/wedding/',
		'mobile-url' => '/wedding/',
		'source-url' => '/weddings/',
    ],
    'sample-campus' => [
        'no-sitemap' => true,
		'name' => '校园志',
        'only' => 'ieale',
		'pc-url' => '/campus/',
		'mobile-url' => '/campus/',
		'source-url' => '/campus/',
    ],
    'sample-work' => [
        'no-sitemap' => true,
		'name' => '右视觉作品',
        'only' => 'iealecn',
		'pc-url' => '/work/',
		'mobile-url' => '/work/',
		'source-url' => '/ysjworks/',
    ],
    'sample-studentwork' => [
        'no-sitemap' => true,
		'name' => '学生作品',
        'only' => 'iealecn',
		'pc-url' => '/studentwork/',
		'mobile-url' => '/studentwork/',
		'source-url' => '/studentworks/',
    ],
    'sample-student' => [
        'no-sitemap' => true,
		'name' => '学生专题',
        'only' => 'iealecn',
		'pc-url' => '/student/',
		'mobile-url' => '/student/',
        'source-url' => '/student/',
    ],
    'sample-show' => [
        'no-sitemap' => true,
		'name' => '作品内容',
		'pc-url' => '/sample/1.html',
		'mobile-url' => '/sample/1.html',
        'source-url' => '/star/811621202.html',
    ],
    'info-train' => [
        'no-sitemap' => true,
		'name' => '招生信息',
        'only' => 'iealecn',
		'pc-url' => '/train/',
		'mobile-url' => '/train/',
        'source-url' => '/train/',
    ],
    'site-map' => [
        'no-sitemap' => true,
		'name' => '网站地图',
        'only' => [],
		'pc-url' => '/sitemap.html',
		'mobile-url' => '/sitemap.html',
        'source-url' => '/sitemap/',
    ],
];
