<?php
return [
    [
        'code' => 'laiyixia',
        'name' => '手机营销系统',
        'domain' => 'http://www.laiyixia.cn',
        'listUrl' => "http://www.laiyixia.cn/news/list_29_{{PAGE}}.html",
        'pages' => 8,
    ],
    [
        'code' => 'baisou',
        'name' => '抓客宝',
        'domain' => 'http://www.shbaisou.com',
        'listUrl' => 'http://www.shbaisou.com/news/14_{{PAGE}}.html',
        'pages' => 6,
    ],
    [
        'code' => 'sousuopai',
        'name' => '搜索派',
        'domain' => 'http://www.sousuopai.net/',
        'listUrl' => 'http://www.sousuopai.net/list/?1_{{PAGE}}.html',
        'pages' => 6,
    ],
    [
        'code' => 'lrblog',
        'name' => '路人竞价',
        'domain' => 'http://www.lrblog.cn',
        'listUrl' => 'http://www.lrblog.cn/ruanjain/shouji/page/{{PAGE}}',
        'pages' => 2,
    ],
    [
        'code' => 'sogou',
        'name' => '访客抓取',
        'domain' => 'http://weixin.sogou.com',
        'listUrl' => 'http://weixin.sogou.com/weixin?query=%E8%AE%BF%E5%AE%A2%E6%8A%93%E5%8F%96&_sug_type_=&sut=2740&lkt=1%2C1483517235433%2C1483517235433&_sug_=y&type=2&sst0=1483517235533&page={{PAGE}}&ie=utf8&w=01019900&dr=1',
        'pages' => 10,
    ],
    [
        'code' => 'sogou',
        'name' => '手机抓取',
        'domain' => 'http://weixin.sogou.com',
        'listUrl' => 'http://weixin.sogou.com/weixin?query=%E6%89%8B%E6%9C%BA%E6%8A%93%E5%8F%96&_sug_type_=&sut=2079&lkt=1%2C1483517214614%2C1483517214614&_sug_=n&type=2&sst0=1483517214716&page={{PAGE}}&ie=utf8&w=01019900&dr=1',
        'pages' => 10,
    ],
    [
        'code' => 'sogou',
        'name' => '手机号抓取',
        'domain' => 'http://weixin.sogou.com',
        'listUrl' => 'http://weixin.sogou.com/weixin?query=%E6%89%8B%E6%9C%BA%E5%8F%B7%E6%8A%93%E5%8F%96&_sug_type_=&sut=2670&lkt=1%2C1483517200348%2C1483517200348&_sug_=y&type=2&sst0=1483517200452&page={{PAGE}}&ie=utf8&w=01019900&dr=1',
        'pages' => 10,
    ],
    [
        'code' => 'sogou',
        'name' => 'QQ号抓取',
        'domain' => 'http://weixin.sogou.com',
        'listUrl' => 'http://weixin.sogou.com/weixin?query=qq%E5%8F%B7%E6%8A%93%E5%8F%96&type=2&page={{PAGE}}&ie=utf8&p=01030402&dp=1',
        'pages' => 10,
    ],
    [
        'code' => 92991,
        'name' => '产品帮助',
        'domain' => 'http://www.92991.com',
        'listUrl' => 'http://www.92991.com/zhishixueyuan/help/list_11_{{PAGE}}.html',
        'pages' => 3,
    ],
    [
        'code' => 92991,
        'name' => '营销知识',
        'domain' => 'http://www.92991.com',
        'listUrl' => 'http://www.92991.com/zhishixueyuan/wangluoyingxiaozhishi/list_12_{{PAGE}}.html',
        'pages' => 8,
    ],
    [
        'code' => 92991,
        'name' => '营销管理',
        'domain' => 'http://www.92991.com',
        'listUrl' => 'http://www.92991.com/zhishixueyuan/yingxiaoguanli/list_10_{{PAGE}}.html',
        'pages' => 5,
    ],
    [
        'code' => '51soudao',
        'name' => '搜道',
        'domain' => 'http://www.51soudao.com',
        'listUrl' => 'http://www.51soudao.com/Class10/index.html',
        'pages' => 1,
    ],
    [
        'code' => '51soudao',
        'name' => '微信营销',
        'domain' => 'http://www.51soudao.com',
        'listUrl' => 'http://www.51soudao.com/Class9/{{PAGE}}/index.html',
        'pages' => 3,
    ],
    [
        'code' => '51soudao',
        'name' => '网络营销',
        'domain' => 'http://www.51soudao.com',
        'listUrl' => 'http://www.51soudao.com/Class8/index.html',
        'pages' => 1,
    ],
    [
        'code' => 'qqluowang',
        'name' => '罗网',
        'domain' => 'http://www.qqluowang.com',
        'listUrl' => 'http://www.qqluowang.com/help/list_3_{{PAGE}}.html',
        'pages' => 11,
    ],
    [
        'code' => 'qqluowang',
        'name' => '罗网',
        'domain' => 'http://www.qqluowang.com',
        'listUrl' => 'http://www.qqluowang.com/about/list_4_{{PAGE}}.html',
        'pages' => 13,
    ],
];
